language: c
script: asdf plugin-test kubefedctl https://github.com/kvokka/asdf-kubefedctl.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
